version: "3.9"

networks:
  pipeline-net:
    external: true

services:
  intent-data-aggregation:
    build: .
    container_name: intent-data-aggregation
    env_file:
      - .env
    restart: always
    networks:
      - pipeline-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
